server.port=8084
spring.application.name=rendezvous-service

# Database H2
spring.datasource.url=jdbc:h2:mem:rendezvousDB
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Consumer ✅ 
spring.kafka.consumer.group-id=rendezvous-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.type.mapping=ma.fsr.eda.patientservice.event.dto.PatientCreatedEvent:ma.fsr.eda.eventdtolib.event.dto.PatientCreatedEvent,ma.fsr.eda.medecinservice.event.dto.MedecinCreatedEvent:ma.fsr.eda.eventdtolib.event.dto.MedecinCreatedEvent,ma.fsr.eda.billingservice.event.dto.FactureFailedEvent:ma.fsr.eda.eventdtolib.event.dto.FactureFailedEvent

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer